version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres-volume:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@user.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: wget --quiet --tries=3 --spider http://localhost:80/misc/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  postgres_network:
    name: postgres_network

volumes:
  postgres-volume:
  pgadmin-volume:

